_gradient_huggingface: &_gradient_huggingface
  origin: https://github.com/graphcore/Gradient-HuggingFace.git
  ref: main


_common_target_repository: &_common_target_repository
    origin: notebooks/
    ref: null

flan-t5:
  source:
    paths:
    - path: natural-language-processing/Flan-T5-generative-inference.ipynb
    - path: natural-language-processing/LICENSE
    - path: natural-language-processing/images/t5_vs_flan_t5.png
    repository:
      <<: *_gradient_huggingface
      prefix: natural-language-processing/
  target:
    repository:
      <<: *_common_target_repository
      prefix: ./

